### PR TITLE
fix: wrong query and mutation in Next.js tutorial

### PR DESCRIPTION
**Pull request by 5t111111**
*Issue #, if available:*

*Description of changes:*

In ["Connect API and database to the app" section of Next.js tutorial](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next), the example query and mutation do not work.

**The schema**:

```graphql
type Post
@model
@auth(rules: [{ allow: owner }, { allow: public, operations: [read] }]) {
  id: ID!
  title: String!
  content: String!
}
```

This `Post` schema does not have either `createdAt` or `updatedAt` field, but there exist in the instructed query and mutation:

```graphql
mutation CreatePost {
  createPost(input: {title: "Test Post", content: "post content"}) {
    id
    owner
    title
    updatedAt
    createdAt
    content
  }
}
```

```graphql
query ListPosts {
  listPosts {
    items {
      content
      createdAt
      id
      owner
      title
    }
  }
}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jamesonwilliams** [comment]
Hey @5t111111! [version 2.17.0](https://github.com/aws-amplify/amplify-cli/blob/f1dc9a05f422dd79327e2f968915a8963f373f6b/packages/graphql-key-transformer/CHANGELOG.md#2170-2020-05-15) of the CLI's GraphQL key transformer starts populating these two fields.

What version are you using?

```console
npm view --no-color graphql-key-transformer | sed -n '2 p;'| cut -f 1 -d' '
graphql-key-transformer@2.20.4
```

**Comment by medelman17** [comment]
@josefaidt, can you take a look at the above and advise whether a change to the documentation is warranted?

**Comment by josefaidt** [comment]
Hey @5t111111 :wave: these two fields, `createdAt` and `updatedAt` are auto-generated and should be available after the resources are pushed. Are you experiencing an issue where these fields are not available?

image

**Comment by medelman17** [comment]
Closing per @josefaidt feedback above. Feel free to open an issue for additional discussion should this re-arise.

**Pull request closed without merging**
