### PR TITLE
(feat): Documentation update to reflect changes from Amplify Swift

### PR DESCRIPTION
**Pull request by royjit**
_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jacoblogan** [comment]
Overall is looking good, just a couple of high level questions regarding versioning the docs.  It looks like the versioned docs only exist for the high level `Libraries` section, but other high level sections that have ios specific docs aren't being versioned (`Getting Started` and `Guides`), do these sections of the docs need to be versioned as well?  The second question is about the `v1` files it looks like all of the files are being duplicated including the ones for android, flutter, and js.  Is it necessary to create versioned documentation for the other platforms as well with this change?

**Comment by royjit** [comment]
> versioned (Getting Started and Guides), do these sections of the docs need to be versioned as well?
We do not need versioning in this sections, it will enable customer to use the latest version if they land on this page.

> Is it necessary to create versioned documentation for the other platforms as well with this change?
@phantumcode do you know why it has to be done this way?

**Comment by atierian** [comment]
Regarding the duplicated documentation in the `lib-v1`, it looks like we can remove it. But we'll also need to remove all fragment references to other platforms within `lib-v1`, otherwise we'll see compiler errors.

Confirmed expected behavior:
- On Swift v2 page (`lib/analytics/record/q/platform/ios/`), selecting Android from dropdown navigates to (`lib/analytics/record/q/platform/android/`).
- On Swift v1 page ((`lib-v1/analytics/record/q/platform/ios/`), selecting Android from dropdown navigates to (`lib/analytics/record/q/platform/android/`).

**Comment by jacoblogan** [comment]
> Confirmed expected behavior:
>    On Swift v2 page (lib/analytics/record/q/platform/ios/), selecting Android from dropdown navigates to (lib/analytics/record/q/platform/android/).
>    On Swift v1 page ((lib-v1/analytics/record/q/platform/ios/), selecting Android from dropdown navigates to (lib/analytics/record/q/platform/android/).

yes that would be the expected behavior, lets get those changes in as a fast follow up to this PR

**Review by jacoblogan — DISMISSED** [review]

**Review by rachelnabors — DISMISSED** [review]
Each guide has been walked through by Swift engineers. Content quality bar has been met. Thank you!

**Review by rachelnabors — DISMISSED** [review]

**Review by jacoblogan — APPROVED** [review]

**Review by rachelnabors — APPROVED** [review]

**Review by rachelnabors — APPROVED** [review]

**Review by jacoblogan — APPROVED** [review]

**Review by jacoblogan — APPROVED** [review]

**Review by rachelnabors — APPROVED** [review]

**Pull request merged**
