### PR TITLE
Updating docs with more descriptive information for 3rd party plugins

### PR DESCRIPTION
**Pull request by renebrandel**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mauerbac — APPROVED** [review]
lgtm

**Review by kaustavghosh06 — APPROVED** [review]

**Comment by r0zar** [comment]
:+1: LGTM as well.

_On a side note..._

It would be nice to get some plugins listed that are not of the 'category' type.

I've been wondering if they could help solve for some of the asks from customers/internally, without having to make core code changes.

That being said, my understanding of their use cases will likely remain fuzzy until I've seen how they are used in a published module.

**Comment by jamesonwilliams** [comment]
> It would be nice to get some plugins listed that are not of the 'category' type.
> 
> I've been wondering if they could help solve for some of the asks from customers/internally, without having to make core code changes.

For Android, iOS, and Flutter, anyway, that's the _only_ type of plugin that can be made. The contract gets defined in the core library, and then the plugin adds the business logic to carry out that contract.

It is not possible to create a plugin that augments/extends the API definition.

**Comment by r0zar** [comment]
Interesting! Didn't know that. Thanks @jamesonwilliams

**Pull request merged**
