### PR TITLE
Hide copy button for console snippets

### PR DESCRIPTION
**Pull request by jpignata**
*Issue #, if available:* n/a

*Description of changes:* Hide copy button for console snippets

Right now, we show the copy button for output that's meant to be
expository rather than a block we expect a developer to copy and paste.
The most common example is CLI output: while this is useful to see to
understand what options should be selected, there's no value in copying
it into your clipboard.

This change suppresses the copy button if the language is set to
"console" which is defined in Linguist. See: https://bit.ly/2XsAkBq

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jpignata** [comment]
**Example**

https://pr-1557.d39agkzf0cwtdz.amplifyapp.com/lib/analytics/getting-started?platform=android

**Comment by jpignata** [comment]
@jordanranz @harrysolovay Ping? No good?

**Comment by jpignata** [comment]
After I get a :thumbsup: from Harry and Jordan, I'll add console as the language to all output snippets.

**Comment by harrysolovay** [comment]
@jpignata lgtm!

**Pull request merged**
