### PR TITLE
fix: provide prop-type on select-mfa-type

### PR DESCRIPTION
**Pull request by watilde**
`ui-component-props` handles `prop-type` as `attr` with no value only for the initial load. Passing a correct `prop-type` fixes an issue that showing `undefined` when user comes from different page which is how the other page manages prop-type.

Fixes: https://github.com/aws-amplify/docs/issues/2705

### CODE REVIEW

**Comment by watilde** [comment]
@sammartinez This is just a friendly reminder that we are waiting for your review. Hope we can fix the issue together :)

**Comment by watilde** [comment]
Ping to keep opening

**Comment by watilde** [comment]
@sammartinez Kindly asking for your review to ship this as the issue is still happening.

**Comment by medelman17** [comment]
Circulated to @aws-amplify/amplify-js internally for review. Apologies for the delay, here.

**Review by medelman17 — APPROVED** [review]

**Pull request merged**
