### PR TITLE
Add promise rejection for AppSync lambda function

### PR DESCRIPTION
**Pull request by renegoretzka**
Added promise rejection for the AppSync lambda function to handle.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by edwardfoyle — APPROVED** [review]

**Review by renebrandel — APPROVED** [review]

**Comment by renebrandel** [comment]
@renegoretzka - hey, we wanted to merge this PR but we've got a conflict now. Do you mind resolving it?

**Comment by renegoretzka** [comment]
@renebrandel yeah, i will do so in the evening. :)

**Comment by medelman17** [comment]
I got you @renegoretzka!

**Comment by renegoretzka** [comment]
Thanks a ton @medelman17!!

**Pull request merged**
