### PR TITLE
Update Storage to include attaching manual policy to Cognito

### PR DESCRIPTION
**Pull request by JSafaiyeh**
https://github.com/aws-amplify/amplify-js/issues/2228

### CODE REVIEW

**Comment by JSafaiyeh** [comment]
Thanks for the review @undefobj. I have attached the policy I used.

**Comment by undefobj** [comment]
Thanks @JSafaiyeh 
@elorzafe can you take an eyeball since this is your area in the CLI and approve if it's good.

**Comment by elorzafe** [comment]
Hi @JSafaiyeh thanks for your PR, but the information you are pointing is not completely accurate.

That policy you mention is only for auth role. For unauth (guest) access you don't want to give write access to private/protected prefix. (identityId for guest credentials change). I would specify that on the doc and also paste the policy for unauth role.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/public/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/uploads/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/protected/*"
            ],
            "Effect": "Allow"
        },
        {
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "public/",
                        "public/*",
                        "protected/",
                        "protected/*"
                    ]
                }
            },
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}"
            ],
            "Effect": "Allow"
        }
    ]
}
``` 

Thanks again

**Comment by JSafaiyeh** [comment]
@elorzafe Thank you for the review. I have specified instructions to attaching the different policies.

**Pull request merged**
