### PR TITLE
Update Codeowners

### PR DESCRIPTION
**Pull request by medelman17**
_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tjleing** [comment]
Hey @medelman17 -- what's the logic here?  Is there a button you can press that creates this kind of PR automatically? 😅

If anything I'd suggest maybe adding `@aws-amplify/documentation-team` to the whole repo, but that might be too much...  I don't want my review to be the only thing on a critical DataStore PR, at least!

At the same time though, it's worth considering being able to rush out PRs that fix a broken link in a section without needing that team's approval.  Interested to hear your feedback!

**Comment by tjleing** [comment]
Ah I imagine this might be from the typo PRs.  Seems like the ideal structure would have two different types of approval that the docs team can access -- a 'soft' approval that also requires the Codeowners' eyes and a 'hard' approval that would bypass that.  Not sure if that's something GitHub supports though.

**Comment by medelman17** [comment]
Right, @tjleing, this is to facilitate reviews of changes that fix small typos, etc..

**Review by mauerbac — APPROVED** [review]
LGTM

**Pull request merged**
