### PR TITLE
Update IAM Policy for CLI

### PR DESCRIPTION
**Pull request by tfentonz**
*Issue #, if available:*
None.

*Description of changes:*
Grants Cognito User Pools method for returning the configuration information and metadata of the specified user pool client.

Grants permission to detach a managed policy from the specified role.
Used by `amplify api remove`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tfentonz** [comment]
@brene I've resubmitted this PR from v2-preview branch as requested.

**Comment by brene** [comment]
@tfentonz - we've just rebased this repo. Now master is the reflecting our production environment. @kaustavghosh06 - can you verify the content?

**Comment by attilah** [comment]
@tfentonz could you please give some information about what operations you did on the schema before the push to reproduce this missing permission problem?

**Comment by mauerbac** [comment]
hey @tfentonz - just wanted to follow-up on this

**Pull request closed without merging**
