### PR TITLE
Update start.md

### PR DESCRIPTION
**Pull request by janhesters**
This is just a small update adding essential commands to the getting started section. I literally spend over an hour figuring these out and collecting them scattered in the docs. I think these are basic commands that should be taught at the very beginning. Furthermore, there should be one place (aka. here) where you can see all commands at a glance.

### CODE REVIEW

**Comment by jordanranz** [comment]
Hey @janhesters,

Thanks for contributing! There is a minor misspelling with 'runnig'.

**Comment by janhesters** [comment]
@jordanranz Fixed! 😊 Thank you.

**Comment by jordanranz** [comment]
This looks good to me. I'd like to have someone from the CLI team approve as well before we merge.

Thanks for contributing @janhesters

**Comment by kvasukib** [comment]
@yuth can you take a look at the PR? Thanks.

**Comment by yuth** [comment]
LGTM

**Comment by sammartinez** [comment]
@yuth Can you approve this please ? Thanks!

**Pull request merged**
