### PR TITLE
Remove Home Page YouTube Embed

### PR DESCRIPTION
**Pull request by jakeburden**
*Issue #, if available:*

*Description of changes:*

Removes YouTube embed from the home page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jakeburden** [comment]
image

**Review by medelman17 — APPROVED** [review]

**Review by mauerbac — APPROVED** [review]

**Comment by tjleing** [comment]
Wait why remove instead of figuring out why the video is down in the first place?  It is admittedly slowing things down but what's the rationale behind this -- are we just pulling it while we figure out the root cause?

**Comment by jakeburden** [comment]
@tjleing I went ahead with merging this since the video is down anyways. Once this video is published again maybe we can bring it back? Open to discussing options with @mauerbac, @medelman17, and team.

**Comment by medelman17** [comment]
Agree with @jakeburden approach; add back once fixed.

**Pull request merged**
