### PR TITLE
move discord link into menu, remove previous discord link, update tests

### PR DESCRIPTION
**Pull request by harrysolovay**
@mauerbac let me know if this looks good to you

Screen Shot 2020-10-21 at 3 12 00 PM

### CODE REVIEW

**Comment by harrysolovay** [comment]
Addresses #2475

**Review by mauerbac — APPROVED** [review]
This is awesome! With Adobe analytics we can also start to track clicks. LGTM

**Review by renebrandel — APPROVED** [review]
LGTM. Please make sure this is tested on mobile as well.

**Comment by mauerbac** [comment]
Screen Shot 2020-10-22 at 11 30 14 AM
Looks great

**Pull request merged**
