### PR TITLE
fix: make table responsive in ui builder section

### PR DESCRIPTION
**Pull request by sowmyadev-kota**
#### Description of changes:

This will replace `HTML table` with Grid component to make it responsive in `UI builder `section.

We have lot of prettier changes in this pr!

Staging site: [https://table-width-issue...amplifyapp.com](https://table-width-issue.d1ywzrxfkb9wgg.amplifyapp.com/)

Testing URL: https://table-width-issue.d1ywzrxfkb9wgg.amplifyapp.com/react-native/build-ui/uibuilder/override/#extend-generated-components-via-overrides-prop

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by jacoblogan — DISMISSED** [review]
LGTM, do we know if there are any other instances of Tables with an image and code snippet that will need to be replaced with a grid?

**Comment by hbuchel** [comment]
It gets real weird at smaller widths where the image sort of disappears). 
Screenshot 2023-11-13 at 4 47 49 PM

Can you try something like this in the page mdx? It's not great, but at least the image doesn't collapse.
```
<Grid templateColumns={{ base: '1fr', large: '240px 1fr' }} gap="small">
  <View maxWidth="240px" margin="auto">
    ![Overriding the color of a text element called
    Title](/images/console/ui-override.png)
  </View>
  <View minWidth="0">
    ```jsx import {FAQItem} from './ui-components' ... ... //⬇️ Element name
    shown in Studio
    <FAQItem overrides={{ Title: { color: 'red' } }} />
    ```
  </View>
</Grid>
```

**Comment by sowmyadev-kota** [comment]
> LGTM, do we know if there are any other instances of Tables with an image and code snippet that will need to be replaced with a grid?

I Think there is no component `AFAK`, but we can add a task for this after `GA` if that is okay?

**Comment by sowmyadev-kota** [comment]
> It gets real weird at smaller widths where the image sort of disappears). Screenshot 2023-11-13 at 4 47 49 PM
> 
> Can you try something like this in the page mdx? It's not great, but at least the image doesn't collapse.
> 
> ```
> <Grid templateColumns={{ base: '1fr', large: '240px 1fr' }} gap="small">
>   <View maxWidth="240px" margin="auto">
>     Overriding the color of a text element called
>     Title
>   </View>
>   <View minWidth="0">
>     ```jsx import {FAQItem} from './ui-components' ... ... //⬇️ Element name
>     shown in Studio
>     <FAQItem overrides={{ Title: { color: 'red' } }} />
>     ```
>   </View>
> </Grid>
> ```

Thank you

**Review by hbuchel — APPROVED** [review]
Thanks @sowmyadev-kota checked it out locally, and the changes LGTM

**Review by katiegoines — APPROVED** [review]

**Review by jacoblogan — APPROVED** [review]

**Pull request merged**
