### PR TITLE
fix: use named import instead of default import

### PR DESCRIPTION
**Pull request by wpyoga**
_Issue #, if available:_ This is done in the same spirit as #4174 and #4175

_Description of changes:_ Now all default imports of `Amplify` are updated to named imports, **except** for those in legacy docs.

Question: Should the legacy docs be updated as well?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by josefaidt — APPROVED** [review]
Hey @wpyoga thank you for your contribution! This looks great!

**Review by chrisbonifacio — APPROVED** [review]

**Comment by josefaidt** [comment]
Hey @wpyoga :wave: apologies for the delay here! Would you mind resyncing your branch with the latest from the main branch?

**Comment by wpyoga** [comment]
@josefaidt I have just Fetched Upstream on my repo -- is it enough to resync with the main repo? (I see that checks have passed)

**Comment by josefaidt** [comment]
Hey @wpyoga thank you! Yes it looks successful 🚢

**Pull request merged**
