### PR TITLE
Add iOS developer menu documentation

### PR DESCRIPTION
**Pull request by eeatonaws**
*Issue #, if available:* N/A

*Description of changes:* Adds documentation for the iOS developer menu to the Amplify iOS library page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mauerbac** [comment]
@jpignata @royjit - is this still pending release ?

**Comment by sebsto** [comment]
Now that Dev Menu has been released in iOS libs 1.4.0 can we release the doc too ?

**Comment by mauerbac** [comment]
@jpignata can we deploy?

**Comment by jpignata** [comment]
@mauerbac Looks like it has approval from the team. @drochetti Any objections?

**Comment by drochetti** [comment]
> @mauerbac Looks like it has approval from the team. @drochetti Any objections?

@jpignata no objections, I just merged. I'll have to follow up with changes since Apple launched a new App lifecycle which isn't covered in the docs yet, but requires some testing to come up with the right docs.

**Pull request merged**
