### PR TITLE
Fix Next.js link & remove from UI drop-down

### LINKED ISSUE #2408: [Feedback] Amplify Next.js getting started
**Page**: [`/start/q/integration/next`](https://docs.amplify.aws/start/q/integration/next?sc_channel=sm&sc_campaign=Mobile_Campaign&sc_publisher=TWITTER&sc_country=Mobile&sc_geo=GLOBAL&sc_outcome=awareness&trk=sm-mobile-community_TWITTER&linkId=99672898)

**Feedback**:

1. Hi there, while trying the tutorial, one thing that I completely missed is that I had to press `SPACE` when selecting "Amazon Cognito User Pool". It would be nice to indicate that next to the terminal output in the getting started page:

`# Amazon Cognito User Pool (press space to select it)`

2. Click on "If you’d like to go ahead and connect the front end, you can jump to the next step." leads to nothing. 

3. Default signup form says phone number is mandatory, it has only US phone numbers. And the code is then sent by email if you do not provide a phone number. This is not very easy to understand (people will stop here). We could ship a version that removes the phone number from the UI (I found that in the AuthController docs)

4. Last deploy step says "Note: Amplify Console is adding support for Server-Side Rendering (SSR). Vote & comment on this issue to show your support!" while I thought it was supported from reading the announcement of amplify + Next.js :) It was fine, but I was surprised

5. Link to UI components renders empty pages like https://docs.amplify.aws/ui/auth/authenticator/q/framework/next

That's it! Thanks :)

### PR DESCRIPTION
**Pull request by ericclemmons**
*Issue #, if available:* Fixes #2408

*Description of changes:*

- [x] Fixes "jump to next step" link
- [x] Fixes drop-downs so Next.js shows up as an integration, but not in UI components or Library.

Screen Shot 2020-09-17 at 12 30 07 PM
Screen Shot 2020-09-17 at 12 30 14 PM
Screen Shot 2020-09-17 at 12 30 21 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@harrysolovay I had to revert 28dcb73b1f04b53a8175d33b4c5c4f13ec69dfc0 because Next.js stopped showing on the https://docs.amplify.aws/start page.

How you recommend I accomplish the following:

- Next.js on https://docs.amplify.aws/start
- Next.js in integration drop-down
- Next.js NOT in filter for UI components

**Comment by mauerbac** [comment]
@sammartinez @harrysolovay - any update on this?

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Comment by mauerbac** [comment]
@harrysolovay , can you take a look at this when you have a chance ?

**Pull request merged**
