### PR TITLE
Add Cognito User Pool Authorizer for REST API override guide to docs.

### PR DESCRIPTION
**Pull request by evankirkiles**
_Issue #, if available:_ [#3390](aws-amplify/amplify-category-api#345) (In the `amplify-cli` repo)

_Description of changes:_ Adds documentation for using overrides with a REST API to create a Cognito User Pool authorizer. I also don't think this would be too much work to just add directly as functionality of the CLI. The actual code used for the guide comes from the gist here: https://gist.github.com/evankirkiles/9de81f026a2e2c961a2b6a3d80d35519, which is a working solution.

Please make any touch-ups to my writing as deemed necessary!

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by jhockett — COMMENTED** [review]
Thanks for the contribution @evankirkiles! I left a couple of suggestions.

**Comment by evankirkiles** [comment]
Thanks, committed the suggestions! @jhockett

**Comment by josefaidt** [comment]
🙌 thanks for submitting this @evankirkiles !

**Review by josefaidt — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

**Comment by josefaidt** [comment]
Hey @evankirkiles :wave: would you mind addressing the PR test failure? It looks like we'll want to add `authtype` to the cspell.json

**Pull request merged**
