### PR TITLE
feat(quickstart): lambda triggers associated

### PR DESCRIPTION
**Pull request by ambientlight**
*Issue #, if available:*
https://github.com/aws-amplify/amplify-cli/pull/2463

*Description of changes:*
`function` category Lambda triggers support associated documentation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by undefobj** [comment]
Hi @ambientlight is this documentation still accurate compared to your PR? I just took a look and seems that the update actions and so forth are on the API category and not Functions category which I believe your PR addresses based on our last feedback.

**Comment by ambientlight** [comment]
> I just took a look and seems that the update actions and so forth are on the API category and not Functions category 

not sure If I understood this right, can you elaborate a bit more?

**Comment by ambientlight** [comment]
@undefobj: oh ok, got the point. Yes, the additional permissions are on storage category, and `Do you want to restrict the access to specific appsync @model(s)?` was changed. Will update, thanks.

**Comment by kaustavghosh06** [comment]
@ambientlight I have opened up a new PR out here - https://github.com/aws-amplify/docs/pull/1178 with all the latest changes which were merged in the CLI repo. Please take a look at it and let me know if I'm missing something out there.

**Pull request closed without merging**
