### PR TITLE
Update screenshot of configure project

### PR DESCRIPTION
**Pull request by changxu0306**
Fix wrong project name in previous configure project screenshot.
Remove a blank line in "initializing Amplify in Java" to make it consistent with that in Kotlin.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jamesonwilliams — APPROVED** [review]
Thanks @changxu0306!

**Review by richardmcclellan — CHANGES_REQUESTED** [review]
It looks like the same image is used for [Getting Started](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#create-a-new-android-application) and [Project Setup](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android), so this fixes Project Setup, but breaks Getting Started.

**Comment by changxu0306** [comment]
> It looks like the same image is used for [Getting Started](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#create-a-new-android-application) and [Project Setup](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android), so this fixes Project Setup, but breaks Getting Started.

Good catch! Will fix it then.

**Comment by richardmcclellan** [comment]
> > It looks like the same image is used for [Getting Started](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#create-a-new-android-application) and [Project Setup](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android), so this fixes Project Setup, but breaks Getting Started.
> 
> Good catch! Will fix it then.

Great!  I think we should just have separate images for each flow, rather than using the same one, that's how iOS handles it.

**Comment by changxu0306** [comment]
> > > It looks like the same image is used for [Getting Started](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#create-a-new-android-application) and [Project Setup](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android), so this fixes Project Setup, but breaks Getting Started.
> > 
> > 
> > Good catch! Will fix it then.
> 
> Great! I think we should just have separate images for each flow, rather than using the same one, that's how iOS handles it.

Yes. That's what I'm doing :-)

**Review by richardmcclellan — APPROVED** [review]

**Pull request merged**
