### PR TITLE
feat: integrate i18n router

### PR DESCRIPTION
**Pull request by watilde**
#### Related issue
https://github.com/aws-amplify/docs/issues/2648

#### Description of changes
This PR is to integrate i18n router as a foundation of further i18n integration and should have no breaking change. There seem to have two different type of documentation in terms of translation system - 1) html files with content json 2) mdx files; The scope of this PR is for the first one and I will make PR for automated mdx converting once we align on this router.

i18n router has two features - 1) Use `en` as a default locale and change nothing with the current website 2) Use local as a prefix for path and router automatically handle routing. Nothing happens if there is no translated resources.

##### Use `en` as a default local
https://localhost:3000/
Screen Shot 2021-11-09 at 11 19 25

##### Use `ja` as a prefix for path
https://localhost:3000/ja/
Screen Shot 2021-11-09 at 11 18 17

##### Use `en` content when translation does not exist
https://localhost:3000/ja/cli/

Screen Shot 2021-11-09 at 11 26 39

### CODE REVIEW

**Comment by watilde** [comment]
CI issue is related to https://github.com/vercel/next.js/issues/18318. I'm investigating to fix now.

**Comment by watilde** [comment]
Turned out `next export` does not support i18n due to this reason: https://github.com/isaachinman/next-i18next/issues/1466#issuecomment-941181172. This seems to be reasonable and we might can start discussion what to do first.

**Comment by watilde** [comment]
Rebased

**Comment by mauerbac** [comment]
Will close in favor of team implementing i18n support

**Pull request closed without merging**
