### PR TITLE
Update advanced.md

### PR DESCRIPTION
**Pull request by nicholaspuglia**
Federated types are in camel case rather than snake case. Found in FederatedConfig type:

`export interface FederatedConfig {
    auth0Config?: {
        audience?: string;
        clientID: string;
        domain: string;
        responseType: string;
        redirectUri: string;
        returnTo?: string;
        scope?: string;
    };
    amazonClientId?: string;
    facebookAppId?: string;
    googleClientId?: string;
    oauthConfig?: {
        [key: string]: any;
    };
}`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mauerbac** [comment]
@elorzafe @sammartinez , can we get a quick review?

**Comment by mauerbac** [comment]
@elorzafe , can you review?

**Review by amhinson — COMMENTED** [review]
It looks like snake case was correct with `aws-amplify-react` ([code](https://github.com/aws-amplify/amplify-js/blob/958f61ef2918728cc46b9b210d60e868edd87f39/packages/aws-amplify-react/src/Auth/FederatedSignIn.tsx#L150-L156)), but the new UI components use camel case ([code](https://github.com/aws-amplify/amplify-js/blob/958f61ef2918728cc46b9b210d60e868edd87f39/packages/amplify-ui-components/src/common/types/auth-types.ts#L24-L40)). 

However, I think this example in the docs would be better served to provide an example for Angular, Vue & React. Perhaps using the `<amplify-block-switcher>` component, i.e.:

```
<amplify-block-switcher>
  <amplify-block name="Angular">
    ...
  </amplify-block>
  <amplify-block name="Vue">
    ...
  </amplify-block>
  <amplify-block name="React">
    ...
  </amplify-block>
</amplify-block-switcher>
```

**Review by amhinson — COMMENTED** [review]
At the least though, we could just update the import and usage:
```
import { AmplifyAuthenticator } from '@aws-amplify/ui-react';

...

<AmplifyAuthenticator federated={federated}>
```

**Pull request closed without merging**
