### PR TITLE
Map Style Add

### PR DESCRIPTION
**Pull request by dayjournal**
_Issue #, if available:_

https://github.com/aws-amplify/amplify-cli/issues/11620
https://github.com/aws-amplify/amplify-cli/pull/11621

_Description of changes:_

- New map styles were added.
    StandardLight (data provided by OpenStreetMap)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by evcodes — APPROVED** [review]

**Review by josefaidt — APPROVED** [review]
LGTM, adding do-not-merge label pending CLI PR review, merge, and release

for reference, on Amplify CLI 10.5.2 we currently see

```
? Specify the map style. Refer https://docs.aws.amazon.com/location-maps/latest/APIReference/API_MapConfiguration.html …  (Use arrow keys or type to filter)
❯ Streets (data provided by Esri)
  Berlin (data provided by HERE)
  Explore (data provided by HERE)
  ExploreTruck (data provided by HERE)
  RasterSatellite (data provided by HERE)
  HybridSatellite (data provided by HERE)
  Topographic (data provided by Esri)
  Navigation (data provided by Esri)
  LightGrayCanvas (data provided by Esri)
  DarkGrayCanvas (data provided by Esri)
  Imagery (data provided by Esri)
```

**Review by goldbez — APPROVED** [review]

**Comment by evcodes** [comment]
Pending release to CLI to be able to add this to the docs site. Please do not merge

**Comment by dayjournal** [comment]
Hi, @evcodes .
This merged pull request does not appear to be included in the v10.6.0 release.
When is it scheduled to be released?

**Comment by dayjournal** [comment]
Hi, @evcodes .
I want to confirm plans for future releases.

**Comment by evcodes** [comment]
Hey @dayjournal, sorry for the delay. This will be out in 10.7. I just tested with the release candidate on NPM so please keep an eye out for v10.7.0 of the CLI [here](https://www.npmjs.com/package/@aws-amplify/cli?activeTab=versions)

**Review by renebrandel — APPROVED** [review]

**Comment by dayjournal** [comment]
Hi, The latest version of Amplify CLI showed the changes.

sample

**Review by hdworld11 — APPROVED** [review]

**Review by timngyn — APPROVED** [review]

**Pull request merged**
