### PR TITLE
exclude password from signIn argument

### PR DESCRIPTION
**Pull request by nubpro**
"To initiate a custom authentication flow in your app, call `signIn` without a password. "

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by medelman17** [comment]
Hi @nubpro, can you give me a bit of background/context re: the underlying problem/issue this PR addresses? I apologize if its elementary, but I want to make sure we're on the same page.

**Comment by nubpro** [comment]
> Hi @nubpro, can you give me a bit of background/context re: the underlying problem/issue this PR addresses? I apologize if its elementary, but I want to make sure we're on the same page.

Sorry about that, let me try to clarify.
https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js#custom_auth-flow
"To initiate a custom authentication flow in your app, **call signIn without a password**. A custom challenge needs to be answered using the sendCustomChallengeAnswer method:"
If we include the password argument, we aren't initiating custom auth challenge.

Hold on, I just realize the doc included this piece of code, which will force the client to use custom auth.
```
Auth.configure({
    // other configurations
    // ...
    authenticationFlowType: 'CUSTOM_AUTH'
});
```

I guess this is a non-issue

**Comment by medelman17** [comment]
Ok to close, @nubpro?

**Comment by nubpro** [comment]
> Ok to close, @nubpro?

Yep

**Pull request closed without merging**
