### PR TITLE
show the installation command for prereq

### PR DESCRIPTION
**Pull request by abdallahshaban557**
#### Description of changes:
Update the installation command in the library guide for all libraries

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [X] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [X] JS
- [X] iOS
- [X] Android
- [X] Flutter
- [X] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by hdworld11 — APPROVED** [review]

**Review by josefaidt — CHANGES_REQUESTED** [review]
I think these are intentionally separated. With this change you would see the install instructions twice on the CLI getting started guide https://github.com/aws-amplify/docs/blob/main/src/pages/cli/start/install.mdx#L22

**Comment by abdallahshaban557** [comment]
> I think these are intentionally separated. With this change you would see the install instructions twice on the CLI getting started guide https://github.com/aws-amplify/docs/blob/main/src/pages/cli/start/install.mdx#L22

I tried checking the getting started guide and I am not seeing duplications in the installation steps there. Is there something I am missing?

**Comment by timngyn** [comment]
@abdallahshaban557 @josefaidt , I made a staging site for the PR. I think Josef is talking about on this page where we see two "Install the Amplify CLI" sections: https://update-cli-steps.d3kzzkiugubm89.amplifyapp.com/cli/start/install/

**Comment by abdallahshaban557** [comment]
Thank you @timngyn  - Josef has clarified this to me as well.

**Review by josefaidt — APPROVED** [review]

**Review by katiegoines — APPROVED** [review]

**Pull request merged**
