### PR TITLE
Removes double declaration

### PR DESCRIPTION
**Pull request by MatthewPMatherne7**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mauerbac** [comment]
hi @MatthewPMatherne7 - thanks for your contribution. We will review this code change. As an FYI - I've removed the ID from this GitHub issue as that is personal information. Please do not upload personal documents to GitHub as it's a public forum.

**Comment by mauerbac** [comment]
nice find @MatthewPMatherne7 . @TrekSoft , do you approve as well?

**Review by mauerbac — APPROVED** [review]
LGTM

**Comment by TrekSoft** [comment]
Hey, this was actually already merged Friday.

**Pull request closed without merging**
