### PR TITLE
Update 40_verifyAmplifyLibraries.mdx

### PR DESCRIPTION
**Pull request by utsavDave97**
Added code markup to main.dart

_Description of changes:_

- The purpose for this change was to have uniformity for the entire Project Setup page as other file names on this page have code markup.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by arundna — DISMISSED** [review]

**Review by offlineprogrammer — APPROVED** [review]

**Comment by utsavDave97** [comment]
Would it be possible to merge this? @offlineprogrammer @arundna

**Comment by fjnoyp** [comment]
Hi @utsavDave97 can we wait for a bit.  It would be best for us to release this feature before merging this docs PR.

**Comment by utsavDave97** [comment]
> Hi @utsavDave97 can we wait for a bit. It would be best for us to release this feature before merging this docs PR.

Understandable. Thanks for quick response.

**Comment by abdallahshaban557** [comment]
We have made some changes to this section and therefore we are closing this PR. Thank you for your contribution @utsavDave97 !

**Pull request closed without merging**
