### PR TITLE
Fix "the" twice used

### PR DESCRIPTION
**Pull request by guikcd**
If first found a "the the" typo on [this page](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react) and then find (thanks `grep`) other occurrences of this typo. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by wlee221 — APPROVED** [review]
11 occurrences 😮  Thanks for catching those!

**Review by dabit3 — APPROVED** [review]

**Review by mauerbac — APPROVED** [review]
Thanks @guikcd ! What is your role at AWS? :)

**Comment by guikcd** [comment]
> Thanks @guikcd ! What is your role at AWS? :)

I'm a Solutions Architect in France.

**Comment by mauerbac** [comment]
@aws-amplify/amplify-native - can we get a review plz

**Review by jpignata — APPROVED** [review]
The the PR looks good to me! Thank you!

**Pull request merged**
