### PR TITLE
Add new guide Cognito/Lambda/DynamoDB

### PR DESCRIPTION
**Pull request by khalidbourhaba**
*Issue #, if available:* https://github.com/aws-amplify/docs/issues/2054

*Description of changes:* Add new guide explaining how to add an entry in DynamoDB table using Cognito triggers and Lambda.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sw-yx** [comment]
@mauerbac what is the process for resolving spellcheck issues like this? need to add USERTABLE to the approvelist

**Comment by mauerbac** [comment]
@sw-yx - looks like you added the term. Just approved and merged.

**Comment by dabit3** [comment]
Thanks @khalidbourhaba , this is a really useful guide!

I know this is already merged, but one improvement could be to update the guide to use the CLI to enable the trigger.

Would you be interested in making this update? If not, we can tackle it soon.

**Comment by khalidbourhaba** [comment]
@dabit3 Thanks, I will look into it !

**Pull request merged**
