### PR TITLE
Adding link to flutter reference docs to top of navigation

### PR DESCRIPTION
**Pull request by rachelnabors**
#### Description of changes:

Adds a "flutter API references" index page to the docs that links out to all the flutter docs on pub.dev, visible only to people who have chosen Flutter as their platform, visible at **docs.amplify.aws/flutter-references**

image

### CODE REVIEW

**Comment by abdallahshaban557** [comment]
@rachelnabors - the only thing I have noticed is that the platform picker disappears when you go to the API references page. Is that expected? Or would we want to add it there as well?

**Comment by rachelnabors** [comment]
I'm guessing if you're on the flutter API page, since there is no alternative in other platforms and you're looking at Flutter docs, it isn't a very useful thing to have!

**Comment by abdallahshaban557** [comment]
got it! approving!

**Review by abdallahshaban557 — DISMISSED** [review]
LGTM

**Review by abdallahshaban557 — APPROVED** [review]
LGTM

**Pull request merged**
