### PR TITLE
replace amplify framework by amplify

### PR DESCRIPTION
**Pull request by MonicaFidalgo**
_Issue:_ [#4691](https://github.com/aws-amplify/docs/issues/4691)

_Description of changes:_
Replacing Amplify Framework with Amplify 

_How to test:_
- Go through Amplify docs and check that we don't have "Amplify Framework"
- Meta tags were also updated
Captura de ecrã 2022-10-15, às 11 37 15

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MonicaFidalgo** [comment]
Hi @rachelnabors could you please have a look at my pr? :) thanks in advance

**Review by katiegoines — APPROVED** [review]
LGTM!

**Review by timngyn — APPROVED** [review]
LGTM!!

**Comment by katiegoines** [comment]
@MonicaFidalgo - thanks so much for taking this on!

hacktober-amplify-2022

**Comment by MonicaFidalgo** [comment]
thank you so much @katiegoines! It was a pleasure! Oh and I love the gif!! such a nice surprise!

**Pull request merged**
