### PR TITLE
[CLI][Hosting] Add "Hosting" Documentation about pulling aws-exports.js

### PR DESCRIPTION
**Pull request by geoseong**
*Issue #, if available:*
#766 

*Description of changes:*
- in `Hosting` in `CLI`
  - append topic: `Build with aws-exports.js in "Continuous deployment" configuration`

I'm working with 2 amplify projects with "Continuous deployment" configuration in `Hosting` Category.

several days ago, I'd got a problem with how to get `aws-exports.js` in Amplify Console's Build. because it keep fails in "Build" step. `aws-exports.js` file is not exist in Build image.

I'd got painful days solving this problem and what I'd tried it is:
- googled it randomly
- tried to follow the guide: [Deploying the Backend with Your Front End](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend)
- and so many other ways to make manual scripts to pull my `aws-exports.js`.
- tried to [Headless mode](https://docs.amplify.aws/cli/usage/headless#amplify-pull-parameters) scripts in `amplify.yml` directly
- issued it to [amplify-console repository](https://github.com/aws-amplify/amplify-console/issues/750) to ask some solution

after challenging several ways I finally got it to work so I've commented on it to my issue, and I think I got a positive response from other people.

so I want to share this topic for those who have painful times like me
that's why I make Pull Request.

Some expressions could be awkward. so I'll correct it If you guys ask to correct something.

Before that, If you guys think this content is not suitable for this document, please tell us why.

Thanks.

### CODE REVIEW

**Comment by sw-yx** [comment]
keep-alive

**Comment by mauerbac** [comment]
@renebrandel , can you review this? Anything else this needs to be merged in @sw-yx ?

**Comment by medelman17** [comment]
Requested technical review internally.

**Comment by mauerbac** [comment]
Updated: https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html

**Pull request closed without merging**
