### PR TITLE
fix: added missing pages

### PR DESCRIPTION
**Pull request by katiegoines**
#### Description of changes:
added pages under Tools > CLI > Custom AWS resources and the Commands page

staging: https://next-release-missing-pages.d1egzztxsxq9xz.amplifyapp.com/

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by hibler13 — COMMENTED** [review]
The individual sections for each command don't resemble those on the existing docs site. For example, compare the current [configure](https://docs.amplify.aws/cli/commands/configure/#configure-project) page with the [next-release version](https://next-release-missing-pages.d1egzztxsxq9xz.amplifyapp.com/react/tools/cli/commands/#configure). The current docs site has subsections for "Usage," "Flags," and "Subcommands." These seem to be represented on the new version of the page, but want to make sure the new approach to displaying these elements will make sense to users. 

One thought: Do we want to treat the terms in the flag section ("--usage-data-on", etc.) as inline code to make it clearer. In the current version, these are also set within a table, which helps with scanning.

**Review by hbuchel — DISMISSED** [review]

**Comment by hbuchel** [comment]
> The individual sections for each command don't resemble those on the existing docs site. For example, compare the current [configure](https://docs.amplify.aws/cli/commands/configure/#configure-project) page with the [next-release version](https://next-release-missing-pages.d1egzztxsxq9xz.amplifyapp.com/react/tools/cli/commands/#configure). The current docs site has subsections for "Usage," "Flags," and "Subcommands." These seem to be represented on the new version of the page, but want to make sure the new approach to displaying these elements will make sense to users.
> 
> One thought: Do we want to treat the terms in the flag section ("--usage-data-on", etc.) as inline code to make it clearer. In the current version, these are also set within a table, which helps with scanning.

Cleaned up some of that here, will let Katie merge after review: https://github.com/aws-amplify/docs/pull/6380

**Comment by katiegoines** [comment]
@hibler13 - Here;s a visual of the changes Heather made: 

> Not a huge change, but move flags into tables and only use the big code block component for the main command. Subcommands and flags use the inline code element.

Screenshot 2023-11-14 at 4 41 04 PM

**Review by hbuchel — APPROVED** [review]

**Review by heatheramz — APPROVED** [review]
Reviewed with Jim - ship it!

**Pull request merged**
