### PR TITLE
chore: added alt text for the images in the flutter library docs

### LINKED ISSUE #5714: Images related to amplify-flutter do not have informative alt text
**Describe the content issue**:
Images listed below don't have descriptive/informative alt text. For markdown the alt text is located between the square brackets, `alt text`.

If the image is for decoration then having an empty string, ``, would be okay, provided that they are non-essential to understanding the content and purpose of the page.

If the image is being used to display info, then we need to have more descriptive text for screen readers. For example, the file `src/fragments/lib/project-setup/flutter/platform-setup/ios.mdx` has an image on line 11 that has `XCode Minimum Deployment Version` for its alt text. The text above it briefly describes how to get to the screen in the screenshot, but for me personally I need to use both the text and image to understand where everything else. We could either make the text above it more descriptive so that the image could be decorative or we could update the alt text of the image to be something like this: `Screenshot for setting the iOS version to 13.0 in the Minimum Deployments section inside the Runner settings window`. I'm not too sure if this would be a correct alt text for the screenshot, but just wanted to give a suggestion!

I was thinking that this issue could be used to track which alt text needs to be updated or can be ignored. Please let me know if you have any questions!

Some resources to help with this:
- https://webaim.org/techniques/alttext/
- https://supercooldesign.co.uk/blog/how-to-write-good-alt-text
```
src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx:
  43: ![XCode Entitlements Screen](/images/project-setup/flutter/mac/xcode-entitlements.png)

src/fragments/lib/project-setup/flutter/platform-setup/ios.mdx:
  11: ![XCode Minimum Deployment Version](/images/project-setup/flutter/ios/target-min-deployment-version.png)
  15: ![XCode Minimum Deployment Version](/images/project-setup/flutter/ios/project-min-deployment-version.png)

src/fragments/lib/project-setup/flutter/platform-setup/macos.mdx:
  13: ![XCode Minimum Deployment Version](/images/project-setup/flutter/mac/target-min-deployment-version.png)
  17: ![XCode Minimum Deployment Version](/images/project-setup/flutter/mac/project-min-deployment-version.png)
  23: ![XCode Entitlements Screen](/images/project-setup/flutter/mac/xcode-entitlements.png)
  41: ![XCode Enable Keychain Sharing](/images/project-setup/flutter/mac/enable-keychain-access.png)
  45: ![XCode Keychain Sharing Search](/images/project-setup/flutter/mac/search-keychain-sharing.png)
  49: ![XCode Adding Keychain Sharing Group](/images/project-setup/flutter/mac/adding-keychain-access-group.png)
  53: ![XCode Signing and Capabilities Screen](/images/project-setup/flutter/mac/enable-signing.png)

src/fragments/lib/storage/flutter/upload.mdx:
  285: ![S3 Metadata](/images/s3_metadata.png)

src/fragments/lib-v1/storage/flutter/upload.mdx:
  116: ![S3 Metadata](/images/s3_metadata.png)

src/fragments/start/getting-started/flutter/integrate.mdx:
  213: ![Budget Tracker home screen](/images/lib/getting-started/flutter/budget-tracker-home.png)
  291: ![Budget Tracker with Authenticator](/images/lib/getting-started/flutter/budget-tracker-authenticator.png)
  494: ![Budget Tracker create screen](/images/lib/getting-started/flutter/budget-tracker-create-screen.png)
  574: ![Completed budget tracker](/images/lib/getting-started/flutter/budget-tracker-complete.png)

src/fragments/ui/auth/developer-preview-callout-flutter.mdx:
  4:   [![authenticator](https://img.shields.io/pub/v/amplify_authenticator.svg)](https://pub.dev/packages/amplify_authenticator)  

```

### PR DESCRIPTION
**Pull request by khatruong2009**
#### Description of changes:
Alt text was added/improved for the images in the flutter library docs.

#### Related GitHub issue #, if available:
Fixes #5714 

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [x] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [x] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [x] JS
- [x] iOS
- [x] Android
- [x] Flutter
- [x] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [x] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [x] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [x] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by timngyn — COMMENTED** [review]
Thank you for this @khatruong2009! Just had a couple of suggestions

**Review by timngyn — APPROVED** [review]
LGTM! Thank you for taking the time to do this!

**Review by abdallahshaban557 — APPROVED** [review]
LGTM!

**Review by abdallahshaban557 — APPROVED** [review]
LGTM

**Review by timngyn — APPROVED** [review]

**Pull request merged**
