### PR TITLE
fix: setup script for Windows

### PR DESCRIPTION
**Pull request by josefaidt**
_Issue #, if available:_

n/a

_Description of changes:_

- changes bash file to js
- adds `setup` script
- adds `postinstall` script
- executes `setup` in `postinstall` (mitigates changing the readme steps)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by timngyn — APPROVED** [review]
Nice job, thank you @josefaidt! Looks good to me. Was able to pull down and it works as expected.

**Comment by timngyn** [comment]
Looking into why the build failed

**Comment by timngyn** [comment]
@josefaidt so I think it's failing because of the `aws-exports.js` file that gets created post install. I pulled the branch down, did `yarn` and then tried to do `amplify pull` and this was the error I got: 
```
Failed to pull the backend.
🛑 Unexpected token 'export'
/Users/timngyn/Development/aws-amplify/pull-requests/docs/src/aws-exports.js:1
export default {}
^^^^^^

SyntaxError: Unexpected token 'export'
...
...
```

**Comment by katiegoines** [comment]
@josefaidt - It looks like you've resolved the build issues, however there are merge conflicts - can you please resolve these? Thank you!

**Review by katiegoines — APPROVED** [review]
LGTM!

**Review by timngyn — APPROVED** [review]
LGTM! Tested it out and it looks like it's working. Thank you Josef!

**Pull request merged**
