### PR TITLE
Draft: Update home page YouTube embed

### PR DESCRIPTION
**Pull request by jakeburden**
*Issue #, if available:*

*Description of changes:*

Updates the YouTube video embed on the home page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jakeburden** [comment]
image

**Comment by tjleing** [comment]
This one sounds better to me than just the straight-up removal...

**Review by tjleing — APPROVED** [review]
Just approving so that if we do decide to go forward with this, we can get it merged immediately!

**Comment by jakeburden** [comment]
Thanks @tjleing for getting this approved ahead of time! Depending on which video we want, we might want to revert [this commit](https://github.com/aws-amplify/docs/pull/3180/commits/253a6477a7808849e5e5211b8acb2aeb053ff55f) (https://github.com/aws-amplify/docs/pull/3180/commits/253a6477a7808849e5e5211b8acb2aeb053ff55f) rather than merging this PR. This PR introduces a new video URL, but reverting that commit will give the previous video URL. I'm not 100% certain which video we'd want to use.

**Pull request closed without merging**
