### PR TITLE
Add a note explaining SDK versioning

### PR DESCRIPTION
**Pull request by palpatim**
Fixes https://github.com/aws-amplify/aws-sdk-ios/issues/1225

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
Also see https://github.com/aws-amplify/docs/pull/825

**Comment by undefobj** [comment]
@palpatim @mlabieniec is this really needed at the start of the quickstart guide? If we need this info can we put it somewhere else or at the end? For instance we could put it here https://aws-amplify.github.io/docs/ios/manualsetup which we link to at the end of the quickstart.

The quickstart is supposed to be just that, a way to get started quickly. We keep on adding stuff that people have to read up front and it intimidates them and slows the on-boarding process.

**Comment by palpatim** [comment]
> @palpatim @mlabieniec is this really needed at the start of the quickstart guide? If we need this info can we put it somewhere else or at the end? For instance we could put it here https://aws-amplify.github.io/docs/ios/manualsetup which we link to at the end of the quickstart.

@undefobj 

Fair point. The other place I could see this being useful would be the "setup/config" section. That's currently labeled in the nav bar as "Manual SDK Setup", and the page itself is titled "Setup Options for the SDK". What about moving it there as a sibling section to the CocoaPods, Carthage, etc docs? 

While we're at it, should we normalize the nav link and page titles to be consistent?

**Comment by undefobj** [comment]
@palpatim 

> Fair point. The other place I could see this being useful would be the "setup/config" section. That's currently labeled in the nav bar as "Manual SDK Setup", and the page itself is titled "Setup Options for the SDK". What about moving it there as a sibling section to the CocoaPods, Carthage, etc docs?

Agree with this, let's do it.

> While we're at it, should we normalize the nav link and page titles to be consistent?

Yes sounds good, the only normalization that was done so far is the main sections (Auth, Storage, etc.) to align with our strategic direction. Everything else is probably up for grabs.

**Comment by palpatim** [comment]
Closing in favor of #865

**Pull request closed without merging**
