### PR TITLE
removes ionic

### PR DESCRIPTION
**Pull request by rachelnabors**
Our Ionic content gets very little traffic, and we lack the deep expertise to keep them up to date regularly. Rather than risk greeting learners with out of date content, we'd like to retire the Ionic tutorial and refocus our efforts on the remaining platforms we've committed to.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by abdallahshaban557 — APPROVED** [review]
LGTM!

**Review by salihgueler — DISMISSED** [review]

**Review by timngyn — DISMISSED** [review]
Lgtm! Tested on staging site and didn't run into any issues

**Review by jacoblogan — DISMISSED** [review]

**Review by katiegoines — COMMENTED** [review]
@rachelnabors, just wanted to note a merge conflict in `src/fragments/start/getting-started/ionic/setup.mdx`

**Comment by rachelnabors** [comment]
@katiegoines Sorry, I'm trying my best to resolve the conflict, but it's not working out. Mind taking a look on your end?

**Review by timngyn — APPROVED** [review]
Looks good!

**Review by jacoblogan — APPROVED** [review]

**Pull request merged**
