### PR TITLE
chore: move js auth events doc out of hub utility

### PR DESCRIPTION
**Pull request by jamesonwilliams**
iOS, Android, and Flutter all document their Auth hub events in the auth
section. JS, on the other hand, had its auth events documented in the
Hub utility section.

In preparation of adding documentation about iOS, Android and Flutter
Hub, we need to streamline the JS Hub documentation a bit.
In other words, the auth events are being moved out of the Hub
documentation in preparation for future work.

Refer: https://github.com/aws-amplify/docs/issues/2471

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by tjleing — APPROVED** [review]
Looks good to me other than this one callout!

**Review by mauerbac — APPROVED** [review]
lgtm

**Comment by mauerbac** [comment]
can @aws-amplify/amplify-native review?

**Review by richardmcclellan — APPROVED** [review]
🚢

**Pull request merged**
